# Generated by Django 4.2 on 2023-05-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_stockrecord_owner'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketline',
            name='stockrecords',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='product.stockrecord'),
            preserve_default=False,
        ),
    ]
