# Generated by Django 4.2 on 2023-05-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basketline_stockrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketline',
            old_name='stockrecords',
            new_name='stockrecord',
        ),
    ]
