# Generated by Django 4.2 on 2023-04-27 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=0.01)]),
            preserve_default=False,
        ),
    ]
