# Generated by Django 4.2 on 2023-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_price_stockrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='partner_sku',
            field=models.CharField(default='a', max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
