# Generated by Django 4.2 on 2023-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productattributevalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
