# Generated by Django 4.2 on 2023-05-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productcategory_slug_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
